  CREATE TABLE "SOUNDMONITORLOG" 
   (	"SOUNDID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DATETIMESTAMP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MICVALUE" NUMBER(4,0), 
	"MESSAGE" VARCHAR2(50), 
	 PRIMARY KEY ("SOUNDID")
  USING INDEX  ENABLE
   ) ;